### PR TITLE
Fix for Edge/WNS2

### LINKED ISSUE #5: Does not work with `wns2-pn1p.notify.windows.com` (Windows Notification Service)
## Error
```
X-Wns-Error-Description: Zero or more than 1 crypto-key <dh> exist. Missing, duplicated or unrecognized field in salt field, dh Count:1 total count:2
```

## Request
See the exact `subscription`, `endpoint`, and `headers` 👇🏻
```json
{
      "message": [
        "push",
        {
          "subscription": {
            "endpoint": "https://wns2-pn1p.notify.windows.com/w/?token=BQYAAAAzkRaRJGmaVL4BeMXavxKoUNo1Q8m4OUUKSQ251R94mg2p%2bO3U%2f6StKGDs%2b1wGnDoAmcYSubYvnp2UTLDWDWBxqeR7ga5EOEut%2flaNJ1juo1OX1Xtddph3l7EDJ7yano8NdmcaHjpIMrCiQg07AYI6KxDNMiJ1vp8l9avmKmPx1cQtIR%2bMDePDVEgrLv5VeB%2fAwemyZUwIwanS2AYFFnjShPl6MeANYjzFICfMyt7vH%2fLOvQKk5N7PRtFBiHprSvxwalqKSFxYVFhlWUhQFS03GOJpOdY25w6%2fPygy79A6VsrBhXgZPBSw5fpkXoZDOU8%3d",
            "expirationTime": null,
            "keys": {
              "p256dh": "BJerTmhy8SaYITwQAOmngeCqZi3MpVPQ-ZTPQGTH0jbCyIsPubRZlfBWKFrKtYVzvHEISUuqLaLBbKdWjK2U46k",
              "auth": "EGOZZZEkmKqLlOkiVrVrYg"
            }
          },
          "payload": {
            "title": "2023-12-01T04:02:18.277Z",
            "body": "You are now subscribed to push notifications!"
          }
        }
      ],
      "level": "warn",
      "timestamp": 1701403338277
    },
    {
      "message": [
        "push",
        0,
        {
          "endpoint": "https://wns2-pn1p.notify.windows.com/w/?token=BQYAAAAzkRaRJGmaVL4BeMXavxKoUNo1Q8m4OUUKSQ251R94mg2p%2bO3U%2f6StKGDs%2b1wGnDoAmcYSubYvnp2UTLDWDWBxqeR7ga5EOEut%2flaNJ1juo1OX1Xtddph3l7EDJ7yano8NdmcaHjpIMrCiQg07AYI6KxDNMiJ1vp8l9avmKmPx1cQtIR%2bMDePDVEgrLv5VeB%2fAwemyZUwIwanS2AYFFnjShPl6MeANYjzFICfMyt7vH%2fLOvQKk5N7PRtFBiHprSvxwalqKSFxYVFhlWUhQFS03GOJpOdY25w6%2fPygy79A6VsrBhXgZPBSw5fpkXoZDOU8%3d",
          "headers": {
            "Encryption": "salt=h9jh4Xejoawr9rf33pg6JA",
            "Crypto-Key": "dh=BGBn_RCTXZCFAm9wp_FC9VXC64-CL3rOBGM3KNL5c-OU8Cq7tuX3UXgcdvy3y5nhg41C9yL4XpIKnRptit4Lqvg; p256ecdsa=BGSDfhpjPGYGwhDoUapYitSda3wkYKVW2DF8Vnp39kcq_IOLPOvJXa1T2VbMvS3Jg40U6WQL85ZAq-yZBTjpdIc",
            "Content-Length": "125",
            "Content-Type": "application/octet-stream",
            "Content-Encoding": "aesgcm",
            "Authorization": "WebPush eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiJodHRwczovL3duczItcG4xcC5ub3RpZnkud2luZG93cy5jb20iLCJleHAiOjE3MDE0NDY1MzgsInN1YiI6IndzQHJ0Lmh0In0.l0vAyI8w0rMSR30Jx4djvJ0yyo1k95MXzcs77Y_TqAUUx4fhKEGq_hbeSQsLRBNH1xQ-Ts15aYQjewTCbhwbSA",
            "TTL": "60",
            "Urgency": "high"
          }
        }
      ],
      "level": "warn",
      "timestamp": 1701403338277
    },

```

### PR DESCRIPTION
**Pull request by CetinSert**
Fixes https://github.com/alastaircoote/webpush-webcrypto/issues/5

### CODE REVIEW

File: lib/payload.js [hunk 1]
```diff
@@ -261,7 +261,7 @@ async function getHeaders({ options, payloadLength, salt, localPublicKey }) {
 
 	const headers = {
 		Encryption: `salt=${base64urlEncode(salt)}`,
-		"Crypto-Key": `dh=${localPublicKeyB64}; p256ecdsa=${appKeyB64}`,
+		"Crypto-Key": `dh=${localPublicKeyB64};p256ecdsa=${appKeyB64}`,
```
Comment (CetinSert) [inline lib/payload.js:264]: @alastaircoote – this is all we need to make it work with Edge!

**Comment by CetinSert** [comment]
@alastaircoote – this single character fixes the issue with Windows servers!

**Comment by stephtr** [comment]
@alastaircoote any chance on this getting merged/published? For me that also fixes the bug without impacting Safari.

**Comment by alastaircoote** [comment]
Sorry for my extremely slow response here, meant to deal with this when @CetinSert commented back in October but was swamped! Published version 1.0.4 with this fix included.

**Comment by stephtr** [comment]
Nice, thank you anyway for your work!
I'll probably soon write a pull request for properly exporting the TypeScript definitions (#7).
